name: Deplog GitHub Pages

on: 
  push:
    branches: 
      - master

permissions:
  contents: read
  pages: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test_and_build_and_deploy:
    runs-on: ubuntu-latest
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 8.6.7
    - run: pnpm ci
    - run: pnpm exsample run build

    - name: Deploy
    uses: peaceiris/actions-gh-pages@v3
    with: 
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./apps/exsample/build