name: Deplog GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.7

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build App
        run: pnpm exsample run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
